# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import digital_doctors_pb2 as digital__doctors__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class DigitalDoctorsAssistantServiceStub(object):
    """==========================
    ===== Service ============
    ==========================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictRisk = channel.unary_unary(
                '/digitaldoctors.DigitalDoctorsAssistantService/PredictRisk',
                request_serializer=digital__doctors__pb2.PredictRiskRequest.SerializeToString,
                response_deserializer=digital__doctors__pb2.PredictRiskResponse.FromString,
                )
        self.PredictTreatment = channel.unary_unary(
                '/digitaldoctors.DigitalDoctorsAssistantService/PredictTreatment',
                request_serializer=digital__doctors__pb2.PredictTreatmentRequest.SerializeToString,
                response_deserializer=digital__doctors__pb2.PredictTreatmentResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/digitaldoctors.DigitalDoctorsAssistantService/HealthCheck',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=digital__doctors__pb2.HealthResponse.FromString,
                )


class DigitalDoctorsAssistantServiceServicer(object):
    """==========================
    ===== Service ============
    ==========================

    """

    def PredictRisk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictTreatment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DigitalDoctorsAssistantServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictRisk': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictRisk,
                    request_deserializer=digital__doctors__pb2.PredictRiskRequest.FromString,
                    response_serializer=digital__doctors__pb2.PredictRiskResponse.SerializeToString,
            ),
            'PredictTreatment': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictTreatment,
                    request_deserializer=digital__doctors__pb2.PredictTreatmentRequest.FromString,
                    response_serializer=digital__doctors__pb2.PredictTreatmentResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=digital__doctors__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'digitaldoctors.DigitalDoctorsAssistantService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DigitalDoctorsAssistantService(object):
    """==========================
    ===== Service ============
    ==========================

    """

    @staticmethod
    def PredictRisk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/digitaldoctors.DigitalDoctorsAssistantService/PredictRisk',
            digital__doctors__pb2.PredictRiskRequest.SerializeToString,
            digital__doctors__pb2.PredictRiskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PredictTreatment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/digitaldoctors.DigitalDoctorsAssistantService/PredictTreatment',
            digital__doctors__pb2.PredictTreatmentRequest.SerializeToString,
            digital__doctors__pb2.PredictTreatmentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/digitaldoctors.DigitalDoctorsAssistantService/HealthCheck',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            digital__doctors__pb2.HealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
